### ISSUE TITLE
Library error in Python 3.10

### ISSUE THREAD

**Issue by igeljaeger** [Gust4Oliveira/Last.fm-Discord-Rich-Presence#18]
the library discord presence uses, uses something for handshake loop that fails because of a loop argument:
```
Starting RPC
Exception in thread Thread-1 (RPCFunction):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/igel/Apps/Last.fm-Discord-Rich-Presence-master/main.py", line 57, in RPCFunction
    User.now_playing()
  File "/home/igel/Apps/Last.fm-Discord-Rich-Presence-master/Last_fm_api.py", line 48, in now_playing
    RPC.enable_RPC()
  File "/home/igel/Apps/Last.fm-Discord-Rich-Presence-master/DiscordRPC.py", line 15, in enable_RPC
    RPC.connect()
  File "/home/igel/.local/lib/python3.10/site-packages/pypresence/presence.py", line 43, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/igel/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 128, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.10/asyncio/streams.py", line 97, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
TypeError: _UnixSelectorEventLoop.create_unix_connection() got an unexpected keyword argument 'loop'
```

**Comment by Gust4Oliveira** [comment]
Just updated all libraries to the latest version, seems fine in Python 3.10.9, give it a try.
